// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // The Prisma CLI (migrate, db pull/push, studio) uses this URL. Migrations
    // must run over the DIRECT connection (:5432), never the pgbouncer pooler
    // (:6543) — pooled connections break DDL and advisory locks. Runtime queries
    // are unaffected: src/lib/prisma.ts builds its own pooled connection from
    // DATABASE_URL via the pg adapter.
    url: env('DIRECT_URL'),
  },
});
