export const CHICKY_OINK_INVENTORY_DISPLAY_ORDER = [
  'regular_chicken',
  'spicy_chicken',
  'regular_liempo',
  'spicy_liempo',
  'liog',
  'spicy_liog',
  'poso',
  'atchara_small',
  'atchara_big',
  'uling',
];

export const IMAGAWAYAKI_INVENTORY_DISPLAY_ORDER = [
  'batter',
  'chocolate',
  'oreo',
  'cheese',
  'custard',
  'minute_maid',
  'mineral_water',
  'cups',
  'straws',
  'blue_lemon',
  'lemon_fruit',
  'sugar',
  'cucumber',
  'cucumber_fruit',
  'straws',
  'ice_cube',
  'bulsita_1',
  'bulsita_2',
  'box_1',
  'box_2',
  'plastic_bag',
];

export const POTATOFRY_INVENTORY_DISPLAY_ORDER = [
  'fries',
  'cheeese_powder',
  'bbq_powder',
  'sour_cream',
  'chili_bbq',
  'small_cups',
  'medium_cups',
  'large_cups',
  'bulsita_3',
];
